import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  ArrowLeftRight,
  ArrowUpCircle,
  ArrowUpDown,
  Ban,
  BarChart3,
  BarChart4,
  BatteryCharging,
  Bell,
  Binary,
  Blocks,
  Brain,
  BrainCircuit,
  Bug,
  ChartLine,
  CheckCircle,
  CircleDollarSign,
  ClipboardCheck,
  ClipboardClock,
  ClipboardList,
  Clock,
  Clock3,
  Coins,
  Copy,
  Cpu,
  Crosshair,
  Disc,
  DollarSign,
  FileText,
  Fingerprint,
  Flame,
  Gauge,
  GitBranch,
  GitMerge,
  Grid3X3,
  HardDrive,
  Heart,
  HelpCircle,
  Inbox,
  Layers,
  Lightbulb,
  Link2,
  Link2Off,
  ListChecks,
  LocateFixed,
  MapPin,
  MapPinned,
  Microscope,
  Minimize2,
  MinusCircle,
  Play,
  PlusCircle,
  RefreshCw,
  Repeat,
  Replace,
  Scan,
  Search,
  SearchCheck,
  Settings2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Square,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Unlink,
  Unplug,
  Wallet,
  Wrench,
  XCircle,
  Zap,
  ZapOff,
  type LucideIcon,
} from "lucide-react";

export const kpiIconMap: Record<string, LucideIcon> = {
  link: Link2,
  unlink: Unlink,
  "alert-triangle": AlertTriangle,
  cpu: Cpu,
  "shield-check": ShieldCheck,
  timer: Timer,
  layers: Layers,
  play: Play,
  target: Target,
  zap: Zap,
  "zap-off": ZapOff,
  clock: Clock,
  "minimize-2": Minimize2,
  "x-circle": XCircle,
  "alert-octagon": AlertOctagon,
  "alert-circle": AlertCircle,
  "check-circle": CheckCircle,
  "git-branch": GitBranch,
  wrench: Wrench,
  "search-check": SearchCheck,
  "help-circle": HelpCircle,
  lightbulb: Lightbulb,
  crosshair: Crosshair,
  scan: Scan,
  gauge: Gauge,
  sparkles: Sparkles,
  "minus-circle": MinusCircle,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  dollar: DollarSign,
  "piggy-bank": TrendingUp,
  memory: Heart,
  heart: Heart,
  shield: Shield,
  binary: Binary,
  fingerprint: Fingerprint,
  activity: Activity,
  microscope: Microscope,
  flame: Flame,
  brain: Brain,
  bell: Bell,
  inbox: Inbox,
  refresh: RefreshCw,
  trash: Trash2,
  blocks: Blocks,
  "memory-stick": HardDrive,
  "map-pin": MapPin,
  ban: Ban,
  replace: Replace,
  grid: Grid3X3,
  copy: Copy,
  "trash-2": Trash2,
  "arrow-up-down": ArrowUpDown,
  "plus-circle": PlusCircle,
  "battery-charging": BatteryCharging,
  bug: Bug,
  "clock-3": Clock3,
  unplug: Unplug,
  "shield-alert": ShieldAlert,
  repeat: Repeat,
  "list-checks": ListChecks,
  "clipboard-check": ClipboardCheck,
  "bar-chart-3": BarChart3,
  search: Search,
  "locate-fixed": LocateFixed,
  "brain-circuit": BrainCircuit,
  square: Square,
  "settings-2": Settings2,
  "clipboard-list": ClipboardList,
  "arrow-up-circle": ArrowUpCircle,
  wallet: Wallet,
  coins: Coins,
  "git-merge": GitMerge,
  "bar-chart-4": BarChart4,
  "file-stack": FileText,
  "file-text": FileText,
  disc: Disc,
  "chart-line": ChartLine,
  network: GitBranch,
  link2off: Link2Off,
  "arrow-left-right": ArrowLeftRight,
  "map-pinned": MapPinned,
  "clipboard-clock": ClipboardClock,
  minimize: Minimize2,
  alert: AlertTriangle,
  "total-test-cost": DollarSign,
  "cost-per-wafer": CircleDollarSign,
  "cost-per-die": Coins,
  yield: TrendingUp,
  "roi-improvement": Sparkles,
};

export function resolveKpiIcon(icon: string | LucideIcon): LucideIcon {
  if (typeof icon !== "string") return icon;
  return kpiIconMap[icon] ?? Sparkles;
}
